CREATE DATABASE data_tables DEFAULT CHARACTER SET utf8mb4;

grant super on *.* to 'mysql.session'@localhost;

grant alter, alter routine, create, create routine, create tablespace, create temporary tables, create user, create view, delete, drop, event, execute, file, index, insert, lock tables, process, references, reload, replication client, replication slave, select, show databases, show view, shutdown, super, trigger, update, grant option on *.* to root;

create table aa
(
    aa_id int auto_increment
        primary key,
    ID varchar(2048) null,
    val int null
);

create table bc_1
(
    bc_1_id int auto_increment
        primary key,
    communityID_x int null,
    bl_fasting int null,
    bl_tg double null,
    bl_top_coding_tg int null,
    bl_crea double null,
    bl_bun int null,
    bl_hdl int null,
    bl_ldl double null,
    bl_cho double null,
    bl_glu int null,
    bl_ua int null,
    bl_cysc int null,
    bl_crp double null,
    bl_hbalc int null,
    communityID_y int null,
    pa001 int null,
    qa002 int null,
    qa002_1 int null,
    qa003 int null,
    qa004 int null,
    qa005 int null,
    qa006 int null,
    qa006_1 int null,
    qa007 int null,
    qa008 int null,
    qa009 int null,
    qa010 int null,
    qa010_1 int null,
    qa011 int null,
    qa012 int null,
    qa013 int null,
    qa014 int null,
    qa016 int null,
    qa017 int null,
    qb002 int null,
    qb003 int null,
    qb004 int null,
    qc003 double null,
    qc004 double null,
    qc005 double null,
    qc006 double null,
    pd001 int null,
    qd004 int null,
    qi002 double null,
    qi003 int null,
    pj001 int null,
    qj002 int null,
    qj003 int null,
    qj004 int null,
    pk001 int null,
    qk002 double null,
    ql002 double null,
    ql003 int null,
    ql004 int null,
    qm002 double null,
    qm005 int null,
    communityID int null,
    ba000_w2_3 int null,
    be001 int null,
    label int null,
    this_county_Insurance int null,
    Set_data int null
);

create table le_225
(
    le_225_id int auto_increment
        primary key,
    communityID_x int null,
    bl_fasting int null,
    bl_tg double null,
    bl_top_coding_tg int null,
    bl_crea double null,
    bl_bun int null,
    bl_hdl int null,
    bl_ldl double null,
    bl_cho double null,
    bl_glu int null,
    bl_ua int null,
    bl_cysc int null,
    bl_crp double null,
    bl_hbalc int null,
    communityID_y int null,
    pa001 int null,
    qa002 int null,
    qa002_1 int null,
    qa003 int null,
    qa004 int null,
    qa005 int null,
    qa006 int null,
    qa006_1 int null,
    qa007 int null,
    qa008 int null,
    qa009 int null,
    qa010 int null,
    qa010_1 int null,
    qa011 int null,
    qa012 int null,
    qa013 int null,
    qa014 int null,
    qa016 int null,
    qa017 int null,
    qb002 int null,
    qb003 int null,
    qb004 int null,
    qc003 double null,
    qc004 double null,
    qc005 double null,
    qc006 double null,
    pd001 int null,
    qd004 int null,
    qi002 double null,
    qi003 int null,
    pj001 int null,
    qj002 int null,
    qj003 int null,
    qj004 int null,
    pk001 int null,
    qk002 double null,
    ql002 double null,
    ql003 int null,
    ql004 int null,
    qm002 double null,
    qm005 int null,
    communityID int null,
    ba000_w2_3 int null,
    be001 int null,
    label int null,
    this_county_Insurance int null,
    Set_table int null
);

create table lr_226
(
    lr_226_id int auto_increment
        primary key,
    communityID_x int null,
    bl_fasting int null,
    bl_tg double null,
    bl_top_coding_tg int null,
    bl_crea double null,
    bl_bun int null,
    bl_hdl int null,
    bl_ldl double null,
    bl_cho double null,
    bl_glu int null,
    bl_ua int null,
    bl_cysc int null,
    bl_crp double null,
    bl_hbalc int null,
    communityID_y int null,
    pa001 int null,
    qa002 int null,
    qa002_1 int null,
    qa003 int null,
    qa004 int null,
    qa005 int null,
    qa006 int null,
    qa006_1 int null,
    qa007 int null,
    qa008 int null,
    qa009 int null,
    qa010 int null,
    qa010_1 int null,
    qa011 int null,
    qa012 int null,
    qa013 int null,
    qa014 int null,
    qa016 int null,
    qa017 int null,
    qb002 int null,
    qb003 int null,
    qb004 int null,
    qc003 double null,
    qc004 double null,
    qc005 double null,
    qc006 double null,
    pd001 int null,
    qd004 int null,
    qi002 double null,
    qi003 int null,
    pj001 int null,
    qj002 int null,
    qj003 int null,
    qj004 int null,
    pk001 int null,
    qk002 double null,
    ql002 double null,
    ql003 int null,
    ql004 int null,
    qm002 double null,
    qm005 int null,
    communityID int null,
    ba000_w2_3 int null,
    be001 int null,
    label int null,
    this_county_Insurance int null,
    Set_data int null
);

create table tt
(
    id int auto_increment
        primary key,
    IDnum varchar(20) null,
    val int null
);

